artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/MdTalha17/Datasets/raw/refs/heads/main/samsumdata.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion